### PR TITLE
Add pg_log_authfail.log_line_prefix paramter to handle ouput format

### PR DESCRIPTION
**Pull request by sttachoires**

### CODE REVIEW

**Comment by rjuju** [comment]
Hello,

Thanks for the interest in this extension! Do you have specific needs for printing lines with the log_line_prefix through this extension, especially not the original one?

I don't really see what it'd used for, at least with fail2ban, so I feel quite hesitant in maintaining the original log_line_prefix() function here.

Best regards.

**Comment by sttachoires** [comment]
My needs are to send connection errors to Splunk via syslog-ng with minimum traffic.
So, quite the same as you for doorman or fail2ban but with customisable line format.
I realize that I forgot to keep the same default output as before, sorry.

**Comment by rjuju** [comment]
That makes sense.

BTW, did you check if you can call log_line_prefix() directly in this hook? After looking shortly at the code, this function is exported and MyProcPort is already allocated at this point. Otherwise, it'd be better to use the main log_line_prefix parameter.

**Comment by sttachoires** [comment]
Yes, and i've seens, looked, and may be wrong :)
It seems to me that i need to rewrite parts of log_line_prefix function.
So, why not use a dedicated log_line_prefix parameter...

2016-06-06 15:30 GMT+02:00 Julien Rouhaud notifications@github.com:

> That makes sense.
> 
> BTW, did you check if you can call log_line_prefix() directly in this
> hook? After looking shortly at the code, this function is exported and
> MyProcPort is already allocated at this point. Otherwise, it'd be better to
> use the main log_line_prefix parameter.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/dalibo/pg_log_authfail/pull/3#issuecomment-223959124,
> or mute the thread
> https://github.com/notifications/unsubscribe/ANWTOKnVydp__rf1A2ECflcbLKI7AqxAks5qJCESgaJpZM4IuX9D
> .

## 

"Vous avez cru jusqu’à ce jour qu’il y avait des tyrans ? Et bien ! vous
vous êtes trompés, il n’y a que des esclaves : là où nul n’obéit, personne
ne commande."
  -- Anselme Belleguarrigue

**Comment by rjuju** [comment]
After looking more closely, Log_line_prefix is exported, but log_line_prefix() isn't, so copying this function is required :(

While at it, I pushed some fix on this extension making. This unfortunately made this PR conflicting. Don't worry about this, if you send updated commits I'll merge them in a single commit on master.

**Comment by sttachoires** [comment]
Hi, i made the modifications as we aggreed by mail.
I merge with your version.
Please use last commit

**Comment by rjuju** [comment]
I just reviewed the patch. I have some last comments:
- any reason you don't support all the log line prefix options (it's missing %c, %p, %s, %i, %v, %x, %e on current head)
- any reason you made use_log_line_prefix PGC_POSTMASTER? PGC_SIGHUP would be more convenient.

**Comment by rjuju** [comment]
Thanks! I merged the commits with some minor cleanup in eaacf452bc5c7da050b68314e9a3b000e3b9dbf6.

I think it'd be useful to be able to change the output or the ident/facility without a restart.  Unless you're willing to also submit a patch for this, I'll do it as soon as possible.

**Pull request closed without merging**
