### PR TITLE
At last...

### PR DESCRIPTION
**Pull request by sttachoires**
Add all_authent parameter to log successfull login too, and change every options to PGC_SIGHUP

### CODE REVIEW

**Comment by rjuju** [comment]
I've reworked the patch so it can apply, and did some additional cleanup.

I've changed the "all_authent" by a "log_success", which is a little different.  As you wrote it, some attempts (resulting in a STATUS_EOF) were logged as successful authentication, which is wrong. Do you want to drop these attempts, or log them (with a different information)?

**Comment by sttachoires** [comment]
Good idea for log_success.
I've got a response from security people, they want it to be logged with a different information ("**Aborded** authentication from HOST on port PORT")
I think adding log_abord parameter

**Comment by rjuju** [comment]
Ok! I committed 5116a579a8e3672d62f706a3b55ee7b744cdd5ff with this modification (also assuming you meant aborted, not aborded).  Can you check if it works as intended?

**Comment by sttachoires** [comment]
Sure I will!
Next week. I'm on a Worshop now. About PostgreSQL 9.6
:D

**Pull request closed without merging**
